version: "3.7"
services:
  mongodb:
    container_name: "db_mongo_dev"
    image: mongo:latest
    environment:
      MONGO_INTIDB_ROOT_USERNAME: root
      MONGO_INTIDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
